name: picarx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - openai
    - SpeechRecognition
    - pyaudio
    - pysox
    - opencv-python
    - readchar
    - setuptools
